- FSharp.Core.Nuget/FSharp.Core.3.1.nuspec
- build.bat
- src/FSharpSource.targets
This is work in progress for #367 builds on top of #364. Removed `MonoAndroid1+MonoTouch1` from other profiles. Ships a single portable library for MonoAndroid, MonoTouch, and Xamarin.iOS. I tested with a local build on Xamarin Studio on Mac and Windows. I'm having a bit a difficulty getting Visual Studio to update to the library. I'm hoping that incrementing the AssemblyVersion will help.
Not yet ready to merge, but this pull request will build a nupkg that we can test.
> portable-net45+monoandroid1+monotouch1+xamarinios1

- FSharp.Core.Nuget/FSharp.Core.3.1.nuspec
- src/FSharpSource.targets
> monodroid & monotouch configured with FX_NO_BIGINT & FX_NO_STRUCTURAL_EQUALITY

- .travis.yml
- tests/projects/build.sh
Disable build of .NET 3.5 projects when using latest Mono
> fix appveyor build

- config.make.in
- src/fsharp/targets.make
Mono 4.0 no longer ships a functioning 4.0 profile. $install/lib/mono/4.0 only has reference assemblies with no IL.
Which means we cannot have fsc.exe there as mono will try to use the mscorlib on that directory and fail.
The solution is to change the build to default to install things on 4.5 and symlink the libraries on 4.0.
> Fix mono 4.0 installation.

- config.make.in
- configure.ac
- src/fsharp/Makefile.in
This is a tentative fix for #391 - only build monotouch and monodroid if PCL bits are also available - the PCL binaries seem to be required by Microsoft.Common.targets.
> Tentative Fix for #391

- src/fsharp/targets.make
This adjusts the fix in #388 to keep the F# targets files installed at the expected canonical path (needed to allow F# project files to compile correctly).
On windows the canonical path still has v4.0 in it even if the .NET framework being used is .NET 4.5.  That's just the way it is
C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0
> adjust #388 to keep targets at canonical locations

- FSharp.Compiler.Tools.Nuget/FSharp.Compiler.Tools.3.1.nuspec
- FSharp.Compiler.Tools.Nuget/build.cmd
- FSharp.Core.Nuget/FSharp.Core.3.1.nuspec
- FSharp.Core.Nuget/build.cmd
- appveyor.ps1
- appveyor.yml
This PR makes each build on AppVeyor be a pre-release build. The idea is to merge this is and then come up with a plan where release builds can be based of of git tags. It is how I do it for SourceLink and at work.
Let's take advantage of the AppVeyor project feed. Can someone with @fsgit credentials, please go here and rename the project feed to `fsharp-fsharp`. You could also use just `fsharp` or `fsgit-fsharp`, but I thought the GitHub repo name was a good convention. Following that convention, I named the feed for my fork `ctaggart-fsharp`. 
https://ci.appveyor.com/project/fsgit/fsharp/settings/nuget
@eiriktsarpalis You can test by adding the feed as a source in `paket.dependencies`.
This fixes #430. Here are the versions in the nupkg.
```
lib\net20\FSharp.Core.dll
2.3.0.0 …
```
> make pre-release builds on AppVeyor

- src/fsharp/FSharp.Core/prim-types.fs
- src/fsharp/FSharp.Core/prim-types.fsi
Undoes part of commit 52a725233, see also https://github.com/Microsoft/visualfsharp/commit/52a7252337983b093c7c0b1e5a4361de259cbe7c#comments
> undo commit 52a725233 which caused binary compat break in FSharp.Core

- config.make.in
- configure.ac
- src/fsharp/FSharp.Build-proto/Makefile.in
- src/fsharp/FSharp.Compiler-proto/Makefile.in
- src/fsharp/Fsc-proto/Makefile.in
- src/fsharp/targets.make
Detect when xbuild is not in PATH (happens on El Capitán), and check
if it's in the standard OSX location. If it is, use the full path
instead of just 'xbuild'.
This makes F# build on El Capitan for Xamarin.iOS and Xamarin.Mac.
> Find xbuild on El Capitan

- README.md
This change also affects Linux, etc. by making the Mono prerequisite clearer.
I also discovered that the build system needs `pkg-config`, also not installed by default on OS X.
> Improved OS X build instructions per issue #482

- .nuget/NuGet.targets
- FSharp.Core.Nuget/.nuget/NuGet.targets
It is not in $PATH anymore if System Integrity Protection is on.
> Find the mono binary on OSX 10.11.

- README.md
This is a quick addition to README.md with some guidelines for performing integrations from Microsoft/visualfsharp to fsharp/fsharp that Don spelled out during a screencast last week.
> added some text about paths to remove/ignore when merging

- .travis.yml
- appveyor.ps1
- autogen.sh
- travis-autogen.sh
This PR enables the build on Travis CI to target multiple OS's and mono versions.
You can look at builds [here](https://travis-ci.org/baronfel/fsharp), though right now they are breaking because of a test that I need to look into.
This would address #499
> Travis multiarch

- README.md
[preview](https://github.com/enricosada/fsharp/blob/b35865b0424ee665c03b376a745e50b2fee63ff1/README.md)
| F#   | Branch        | OSX/Linux | Windows |
|------|---------------|-----------|---------|
| 4.0+ | ``master``    | [![Build Status](https://travis-ci.org/fsharp/fsharp.png?branch=master)](https://travis-ci.org/fsharp/fsharp/branches) | [![Build status](https://ci.appveyor.com/api/projects/status/7m5e2yr0snbbr7t9)](https://ci.appveyor.com/project/fsgit/fsharp) |
| 4.0  | ``fsharp4``   | [![Build Status](https://travis-ci.org/fsharp/fsharp.png?branch=fsharp4)](https://travis-ci.org/fsharp/fsharp/branches) |
| 3.1  | ``fsharp31``  | [![Build Status](https://travis-ci.org/fsharp/fsharp.png?branch=fsharp31)](https://travis-ci.org/fsharp/fsharp/branches) |
| 3.0  | ``fsharp_30`` | …
> Use a table to display the build matrix

- lib/bootstrap/4.0/Microsoft.FSharp.Targets
- src/fsharp/FSharp.Build/Microsoft.FSharp.Targets
4.0/Mono.Posix.dll is not guaranteed to exist, on Mono 4.0+
> Assume we are inside XBuild when 4.5/Mono.Posix.dll exists

- .travis.yml
we should always build and test with latest mono, but it may break the build sometimes, it's ok
if a `Mono: latest` build job fails ( both osx and linux ) the build should not fail
with this, we dont need to disable tests ( like #518 ) and we know when the problem is fixed
see this pr travis build
> allow failures on mono latest

- configure.ac
I'm not sure if we deliberately did this, but everyone should be using Mono 4 now anyway.
> Adjust mono requirements and F# version

- configure.ac
Previous commit[1] that changed this variable didn't update the
reasoning employed in the warning message.
[1] https://github.com/fsharp/fsharp/commit/ee089bfb434c6b2d96d5fa2da4b8e53958b69dd9
> configure: adjust new reason for recommending higher Mono version

- src/FSharpSource.targets
In order to build using prompt (build.bat), solution dir need to be specified.
However, it should not interfere with what visual studio considers to be the solution dir (by using FSharpSourcesRoot variable instead).
> VS2015 and VS2013 does not allow change of SolutionDir

- .travis.yml
I'm hopeful that https://github.com/fsharp/fsharp/issues/528 has been fixed in Mono latest. It is present in Mono 4.2.2.  So let's try turning on allow-failures for Mono 4.2.2 and turning it off for Mono latest.
> Allow failures in Mono 4.2.2 but not latest

- src/FSharpSource.targets
- src/fsharp/FSharp.Build/Microsoft.Portable.FSharp.targets
Remove old Mono workarounds.
One is dead code, the other breaks on Mono 4.6+.
Note that this will probably break on Mono < 4.6.
> Remove old Mono workarounds

- FSharp.Core.Nuget/FSharp.Core.nuspec
FSharp.Core . 4.4.1 is not compatible with net40 and should therefore be not packaged in the net40 folder.
Two open questions:
- What about the net20 folder: Currently we package:
(Note the Platform ".Net Framework v4.6.1", maybe we should just drop that one?)
- I'm still unsure if we should it move out of the `.NETFramework\v4.0` folder as well?
Otherwise this should work and fix the immediate issue in https://github.com/fsharp/fsharp/issues/672
> fix packaging of FSharp.Core

- appveyor.ps1
- lib/netcore/fsc/project.json
to update `FSharp.Compiler.Tools` package with new `FSharp.Build.dll`, required to enable FSAC on new fsproj
Followup of https://github.com/Microsoft/visualfsharp/issues/2625
as a note, i used version `4.1.1`, so from now on we can use major.minor.patch (ref #682)
i am testing of integration of all packages with https://github.com/dotnet/netcorecli-fsc/pull/88 and another PR in vscode to test FSAC.
> Refresh compiler tools

- tests/fsharp/core/queriesLeafExpressionConvert/test.fsx
- tests/fsharp/core/quotes/test.fsx
PR #518 disabled some test cases due to an issue with Mono 4.2.x. The bug was fixed later in the 4.2.x builds. The current stable mono build is now 4.8.x, and anyone who's working with this repo (and running the test cases) should be running at least 4.6.x, so let's re-enable these test cases for parity with the Microsoft/visualfsharp repo.
> Revert PR #518 to re-enable test cases

- FSharp.Compiler.Tools.Nuget/FSharp.Compiler.Tools.nuspec
- FSharp.Compiler.Tools.Nuget/build/FSharp.Compiler.Tools.props
This is a continuation of https://github.com/fsharp/fsharp/pull/675
With the changed templates from https://github.com/Microsoft/visualfsharp/pull/2575 this should allow to override the .targets without needing to modify the fsproj. (Obviously only for new projects created with these templates).
TODO: what about portable targets? I think we would need to include ``Microsoft.Portable.FSharp.Targets`` in the nuget and set ``PortableFSharpTargetsPath``.
-------------
I have tested that the Condition evaluates to true when using the old sdk.
Will try to create a net core environment where I can test this, it looks like net core as installed with VS is broken ...
__Edit:__
The issue was that you need to run ``dotnet restore`` after ``dotnet new console -lang F#`` and before ``dotnet build``, …
> FSharp.Compiler.Tools: set FSharpTargetsPath when using the old SDK

- src/fsharp/FSharp.Build/Microsoft.FSharp.targets
- 948e2c78e4dec774e07b82adfd8f5c240adfb621 added the generated
AssemblyAttribute file to `@(CompileBefore)` or `@(CompileAfter)`
depeding on `$(OutputType) == 'Exe'`. But this broke projects which
have `$(OutputType) == 'WinExe'`, for which it was added to
`@(CompileAfter)`.
This manifested as:
Tool /Library/Frameworks/Mono.framework/Versions/5.0.0/lib/mono/fsharp/fsc.exe execution started with arguments:  -o:obj/x86/Debug/MonoSuite.FSharpGTK.exe
-g
--debug:full
--noframework
--define:DEBUG
--optimize-
--tailcalls-
--platform:x86
-r:/Library/Frameworks/Mono.framework/Versions/5.0.0/lib/mono/4.5-api/mscorlib.dll
-r:/Library/Frameworks/Mono.framework/Versions/5.0.0/lib/mono/gac/FSharp.Core/4.4.1.0__b03f5f7f11d50a3a/FSharp.Core.dll
-r:/Library/Frameworks/Mono.framework/Versions/5.0.0/lib/mono …
> [msbuild] Fix regression in Microsoft.Build.FSharp.targets

- src/fsharp/targets.make
After this change I see the following symlinks installed
```
21:50 $ ls -la /Library/Frameworks/Mono.framework/Versions/5.0.0/lib/mono/4.5/FSharp.*
lrwxr-xr-x  1 root  admin  60 Apr 10 21:50 /Library/Frameworks/Mono.framework/Versions/5.0.0/lib/mono/4.5/FSharp.Core.dll -> ../gac/FSharp.Core/4.4.1.0__b03f5f7f11d50a3a/FSharp.Core.dll
lrwxr-xr-x  1 root  admin  64 Apr 10 21:50 /Library/Frameworks/Mono.framework/Versions/5.0.0/lib/mono/4.5/FSharp.Core.optdata -> ../gac/FSharp.Core/4.4.1.0__b03f5f7f11d50a3a/FSharp.Core.optdata
lrwxr-xr-x  1 root  admin  64 Apr 10 21:50 /Library/Frameworks/Mono.framework/Versions/5.0.0/lib/mono/4.5/FSharp.Core.sigdata -> ../gac/FSharp.Core/4.4.1.0__b03f5f7f11d50a3a/FSharp.Core.sigdata
lrwxr-xr-x  1 root  admin  60 Apr 10 21:50 …
```
> Add missing symlinks. Fixes #711

- FSharp.Core.Nuget/FSharp.Core.nuspec
@enricosada can you review?
Download and inspect https://www.nuget.org/packages/Microsoft.FSharp.Core.netcore.
This change ensures that `FSharp.Core.optdata` and `FSharp.Core.sigdata` are copied to the output directory when publishing with dnc.
> Package like Microsoft.FSharp.Core.netcore

- FSharp.Core.Nuget/FSharp.Core.nuspec
- appveyor.ps1
Adding these "content" files to FSharp.Core has caused issues.  
Users of this package who want to do compilation at runtime should find other ways of making sure the relevant files are deployed along with their project, e.g. 
- by using explicit "content" or "Copy" entries for specific versions of the files, adding these entries to their project file, and directly referencing the files from the relevant "lib" directory of the project (TODO: add an example of what's needed)
- or else acquire and cache a fresh copy of the FSharp.Core nuget package when their application runs, perhaps by using a package management tool
> revert addition of content to FSharp.Core nuget

- src/fsharp/Fsc/fsc.exe.config
the 'System.Collections.Immutable' referenced by fsc is 1.2.0.0 and is also the one
contained inside the nupkg
both `FSharp.Compiler.Tools` 4.1.5 has an issue (bundle 1.2.0 but reference 1.2.1)
and latest (4.1.14) who has a binding redirect to 1.2.1 but ref and bundle 1.2.0
> fix fsc binding redirect

- mono/travis-autogen.sh
- tests/fsharp/core/run-opt.sh
- tests/fsharp/core/syntax/test.fsx
A test is failing on Mono macOS after the last integration.  Not sure why, it seems like the test is not running the updated installed version of the F# compiler.  Here are some diagnostics to help work out why
> Fix failing test

- src/fsharp/FSharp.Core/result.fsi
The doc strings for `Result.mapError` appear to be copied from `Result.map` without any changes. I updated to reflect the meaning of the function.
> fix intellisense for Result.mapError

- CHANGELOG-fsharp.md
- FSharp.Compiler.Tools.Nuget/FSharp.Compiler.Tools.nuspec
- src/fsharp/CompileOps.fs
We are getting this error from FSharp.Compiler.Tools
[00:02:34]   EXEC : error FS0193: Could not load file or assembly 'System.ValueTuple, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. [C:\projects\fsharp\src\fsharp\Fsc-proto\Fsc-proto.fsproj]
[00:02:34]   C:\projects\fsharp\src\scripts\fssrgen.targets(27,5): error MSB3073: The command ""C:\projects\fsharp\packages\FSharp.Compiler.Tools.4.1.21\tools\fsi.exe" --exec "C:\projects\fsharp\src\scripts\fssrgen.fsx" "C:\projects\fsharp\src\fsharp\FSComp.txt" "obj\net40\FSComp.fs"  "obj\net40\FSComp.resx" " exited with code 1. [C:\projects\fsharp\src\fsharp\Fsc-proto\Fsc-proto.fsproj]
This should fix that
> add System.ValueTuple.dll to nuget package and fix default reference

- Makefile
- configure.ac
- mono/config.make.in
These build settings are no longer needed now we are just packaging the binaries from the old nuget package
> cleanup flags

- Makefile
`ls` was returning a non-zero error code on OSX when installing due to the msbuild folder being in a different location to linux. 
As this looks as if it's for information purposes only, I changed it to ignore any error code coming from the `ls` command.
> Ignore error code from ls

- src/fsharp/FSharp.Build/CreateFSharpManifestResourceName.fs
- src/fsharp/FSharp.Build/CreateFSharpManifestResourceName.fsi
- src/fsharp/FSharp.Build/Fsc.fs
- src/fsharp/FSharp.Build/Fsc.fsi
- src/fsharp/FSharp.Build/Microsoft.FSharp.Targets
Given a resource in a folder named `AFolder/AResourceFile.txt` in a project with
a root namespace of `fsharpresources`, then the following command line arg
should be passed to the compiler
```
--resource:AFolder/AResourceFile.txt,fsharpresources.AFolder.AResourceFile.txt
```
whereas currently it just passes the name of the file. This also fixes passing
a `LogicalName` to the resource.
Fixes https://github.com/Microsoft/visualfsharp/issues/1050 &&
https://github.com/Microsoft/visualfsharp/issues/922
I looked at how Roslyn was doing this [here](https://github.com/dotnet/roslyn/blob/6847f1e5a909395aae9456e8f366cbf4deb86b69/src/Compilers/Core/MSBuildTask/ManagedCompiler.cs#L739)
> Make F# resources work more like C#

- README.md
provides a binary installation of the 5.2 stable version of mono's OSX packaging
> mention the `mono-mdk` cask

- .travis.yml
- mono/prepare-mono.sh
New builds fail because mono packages repository is for a different distro than the Travis environment one (#773 - more on #776 comments). 
* Move to Trusty-based Travis environment.
* Switch to mono packages repository for Ubuntu Trusty (from Debian Wheezy).
> Fix missing msbuild on Travis build (#773).

- mono/config.make.in
So that F# .NET Core 2.0 templates can be built with VS for Mac and
Mono msbuild. Re: https://bugzilla.xamarin.com/show_bug.cgi?id=57771
Searching the .NET Core sdk files we see:
/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.FSharp.props:
```
<FSharpPropsShim Condition = " '$(FSharpPropsShim)' == '' and Exists('$(MSBuildToolsPath)\FSharp\Microsoft.FSharp.NetSdk.props') ">$(MSBuildToolsPath)\FSharp\Microsoft.FSharp.NetSdk.props</FSharpPropsShim>
<FSharpPropsShim Condition = " '$(FSharpPropsShim)' == '' and Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.NetSdk.props') ">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.NetSdk.props</FSharpPropsShim>
<Import Condition=" …
```
> Install Microsoft.FSharp.NetSdk.props and targets into Mono

- README.md
Adds a command to the readme to quickly remove multiple files that are no longer present when integrating visualsharp.
> Add command to remove deleted files in merge

- .gitignore
- src/fsharp/FSComp.txt
- src/fsharp/IlxGen.fs
- src/fsharp/TcGlobals.fs
- src/fsharp/TypeRelations.fs
- src/fsharp/fsc.fs
- src/fsharp/service/ServiceUntypedParse.fs
- src/fsharp/service/ServiceUntypedParse.fsi
- src/fsharp/service/service.fs
- src/fsharp/service/service.fsi
- src/fsharp/xlf/FSComp.txt.cs.xlf
- src/fsharp/xlf/FSComp.txt.de.xlf
- src/fsharp/xlf/FSComp.txt.en.xlf
- src/fsharp/xlf/FSComp.txt.es.xlf
- src/fsharp/xlf/FSComp.txt.fr.xlf
- src/fsharp/xlf/FSComp.txt.it.xlf
- src/fsharp/xlf/FSComp.txt.ja.xlf
- src/fsharp/xlf/FSComp.txt.ko.xlf
- src/fsharp/xlf/FSComp.txt.pl.xlf
- src/fsharp/xlf/FSComp.txt.pt-BR.xlf
- src/fsharp/xlf/FSComp.txt.ru.xlf
- src/fsharp/xlf/FSComp.txt.tr.xlf
- src/fsharp/xlf/FSComp.txt.zh-Hans.xlf
- src/fsharp/xlf/FSComp.txt.zh-Hant.xlf
- tests/fsharp/core/subtype/test.fsx
- tests/projects/Sample_NETCoreSDK_FSharp_Library_netstandard2_0/Library1.fs
- tests/projects/Sample_NETCoreSDK_FSharp_Library_netstandard2_0/Sample_NETCoreSDK_FSharp_Library_netstandard2_0.fsproj
@dsyme I appreciate the direction getting started with this.  I went through the steps pulling in two additional commits compared to #808, however 30 _fewer_ files were changed.  The difference seems to be the files being removed under src/fsharp/xlf.  Should I remove those as well?
One additional note, build succeeds but tests fail with the following - any suggestions or might this be my environment (Docker `mono:latest` image):
```
Running libtest....OK
Running int32....OK
Running attributes....OK
FAILURE: math/measures/test.fsx - System.InvalidProgramException: Invalid IL code in Core_genericMeasures:foo (): IL_0005: stloc.0   
at Core_genericMeasures.RunAll () [0x00000] in <5a61567b229e38e0a74503837b56615a>:0 
at Core_genericMeasures.RUN[a] () [0x00000] in …
```
> integration from visualfsharp master

- src/scripts/scriptlib.fsx
We need to be explicit about the type of switchName as
String.StartsWith recently got a new char overload during the
last corefx import.
Fixes https://github.com/mono/mono/issues/7805
> Fix build on latest mono

- src/scripts/scriptlib.fsx
The CoreFX addition of new overloads to very basic methods such as `GetFileName` has busted some F# code.
Trying to patch up the build here
> fix build failure on Mono latest

- build/targets/CommonPackages.targets
- build/targets/ConvertPortablePdbs.targets
- build/targets/GenerateAssemblyAttributes.targets
- build/targets/GenerateInternalsVisibleTo.targets
- src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj
- src/fsharp/FSharp.Build/FSharp.Build.fsproj
Major caveat: I don't actually know what I am doing.
Instead of creating my comment as an issue I have made it a pull request.
When I try to run the build (build.bat) with MSBuild 12.0 the build tools complain that there are missing xmlns attributes on the .target Project tags, and that they do not understand the new(?) inlined CopyToOutputDirectory attributes for the None tags in the .fsproj files.
Can this be fixed, or will it just ruin other scenarios instead?
> Downgrade build script for MSBuild 12.0.
