fsharp/fsharp

.travis.yml

Trial using the "csharp" Linux environment on Travis to reduce install times

trial using latest mono

---

.gitignore
src/fsharp/FSComp.txt
src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj
src/fsharp/FSharp.Build/CreateFSharpManifestResourceName.fs
src/fsharp/FSharp.Build/FSharp.Build.fsproj
src/fsharp/FSharp.Build/Fsc.fs
src/fsharp/FSharp.Build/Microsoft.FSharp.Targets
src/fsharp/FSharp.Build/Microsoft.Portable.FSharp.Targets
src/fsharp/FSharp.Compiler-proto/FSharp.Compiler-proto.fsproj
src/fsharp/FSharp.Compiler.Interactive.Settings/FSharp.Compiler.Interactive.Settings.fsproj
src/fsharp/FSharp.Core.Unittests/FSharp.Core.Unittests.fsproj
src/fsharp/FSharp.Core.Unittests/FSharp.Core/Microsoft.FSharp.Collections/StringModule.fs
src/fsharp/FSharp.Core.Unittests/FSharp.Core/Microsoft.FSharp.Reflection/FSharpReflection.fs
src/fsharp/FSharp.Core/array.fs
src/fsharp/FSharp.Core/control.fs
src/fsharp/FSharp.Core/local.fs
src/fsharp/FSharp.Core/prim-types.fs
src/fsharp/FSharp.Core/prim-types.fsi
src/fsharp/FSharp.Core/printf.fs
src/fsharp/FSharp.Core/seq.fs
src/fsharp/ast.fs
src/fsharp/build.fs
src/fsharp/csolve.fs
src/fsharp/fscopts.fs
src/fsharp/fsi/console.fs
src/fsharp/fsiAnyCpu/FsiAnyCpu.fsproj
src/fsharp/infos.fs
src/fsharp/tast.fs

this merge some changes from visualfsharp repo
the whitespace cleanup is done to make easier to compare files of the visualfsharp repo 
now all differences with the `src` directory are bugfix, features or infrastructure
There is also the parallel pr Microsoft/visualfsharp#252 to visualfsharp repo

Easier compare of visualfsharp

---

Makefile.in
src/fsharp/Makefile.in

This makes our (combined) Xamarin.iOS and Xamarin.Mac build about 70 seconds faster.

Faster builds

---

.gitignore
appveyor.ps1

This continues #433 and fixes #434.

stable versions created from Git tags

---

FSharp.Compiler.Tools.Nuget/FSharp.Compiler.Tools.3.1.nuspec

Fix #445 - FSharp.Compiler.Tools nuget should include the signed FSharp.Core

---

FSharp.Core.Nuget/FSharp.Core.3.1.nuspec

I can test this after it builds.

added trailing zero for Paket compatibility

---

tests/fsharp/core/queriesLeafExpressionConvert/test.fsx
tests/fsharp/core/quotes/test.fsx

Disable two tests that are failing on Mono master https://github.com/fsharp/fsharp/issues/517

Disable tests failing 517

---

src/fsharp/CompileOps.fs
tests/fsharp/core/attributes/test.fsx
tests/fsharp/core/fsiAndModifiers/test.fsx

Adds a fix and test for https://github.com/fsharp/fsharp/issues/483.  Previously the test failed when using simple (mono) resolution

add fix and test for 483

---

src/fsharp/TastOps.fs
src/fsharp/TypeChecker.fs
tests/fsharp/core/seq/test.fsx

Cherry pick the fix for the loop optimization bug from Microsoft/visualfsharp#756
It would be best not to apply this until the build and fix has been fully validated though

fix problem with loop optimization

---

build.bat
configure.ac
packages.config
src/FSharpSource.targets
tests/projects/Sample_VS2012_FSharp_ConsoleApp_net45_with_resource_using_bootstrap/Sample_VS2012_FSharp_ConsoleApp_net45/Sample_VS2012_FSharp_ConsoleApp_net45.fsproj

Per discussion in https://github.com/fsharp/fsharp/issues/591

update tools to 4.0.1.3

---

src/fsharp/FSharp.Compiler.Interactive.Settings/Makefile.in
src/fsharp/FSharp.Compiler.Server.Shared/Makefile.in
src/fsharp/FSharp.Core/Makefile.in
src/fsharp/targets.make

Try to fix https://github.com/fsharp/fsharp/pull/614

add optdata/sigdata

---

.nuget/NuGet.Config
appveyor.ps1
packages.config

Remove myget from nuget resolution list, may plausibly fix #617

simplify dependencies

---

src/fsharp/FSharp.Build/Fsc.fs

Cherry-picking https://github.com/Microsoft/visualfsharp/pull/1638

Fix fsc task to check for nulls

---

src/fsharp/FSharp.Build-proto/Microsoft.FSharp-proto.targets
src/fsharp/FSharp.Build/Microsoft.FSharp.targets

Fix FSharp.Build to support various F# 4.0/4.1 flags

fix targets for F# 4.1 flags

---

src/absil/ilreflect.fs

Possible fix for https://github.com/fsharp/fsharp/issues/639. It seems like we may have hit this issue before

Possible fix for 639

---

src/fsharp/CompileOps.fs

Cherry picked commit to FSharp.Compiler.Service https://github.com/fsharp/FSharp.Compiler.Service/pull/683

Switch order of Mono search paths

---

CHANGELOG-fsharp.md
appveyor.ps1
src/fsharp/CompileOps.fs
src/fsharp/MSBuildReferenceResolver.fs

https://github.com/fsharp/fsharp/issues/656

Fix 656 - no access to the given key

---

FSharp.Compiler.Tools.Nuget/build/FSharp.Compiler.Tools.props

ref https://github.com/fsharp/FSharp.Compiler.Service/issues/721

fix https://github.com/fsharp/FSharp.Compiler.Service/issues/721

---

appveyor.ps1
src/fsharp/FSharp.Build/Fsc.fs
src/fsharp/FSharp.Build/Fsc.fsi
src/fsharp/FSharp.Build/Microsoft.FSharp.targets
tests/projects/dotnetsdk/1.0.1/console-netcoreapp1_0/Program.fs
tests/projects/dotnetsdk/1.0.1/console-netcoreapp1_0/c1.fsproj
tests/projects/dotnetsdk/1.0.1/library-netstandard1_6/Library.fs
tests/projects/dotnetsdk/1.0.1/library-netstandard1_6/l1.fsproj

ref #684
align fsc task and target file

Sync fsc task

---

src/fsharp/targets.make

I made a mistake with my last commit to this file. This corrects it. Thanks!

Fix mono/gac location

---

Makefile.in
configure.ac

Hopefully fixes https://github.com/fsharp/fsharp/issues/725

Fix brew build: remove redundant explicit copy

---

FSharp.Core.Nuget/FSharp.Core.nuspec

Grab the files from the right output directory

fix nuspec

---

Makefile
src/fsharp/fsi/fsimain.fs

fix fsharpi gui message

---

CHANGELOG-fsharp.md
mono/appveyor.ps1
src/fsharp/TastOps.fs
src/fsharp/TypeChecker.fs
tests/fsharp/core/subtype/test.fsx

This fix is needed in the Mono releases https://github.com/Microsoft/visualfsharp/pull/4804

Cheery pick https://github.com/Microsoft/visualfsharp/pull/4804

---

README.md

This adds support for all distros

Add Linuxbrew
